add validation to the code
hotwax/launchpad pull request #61
Opened 2023-10-13 08:54 UTC by priyanshee1604

### Related Issues

Closes #

### Short Description and Why It's Useful

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [ ] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

2023-10-13 08:56 UTC, priyanshee1604 commented
i tried to resolve the error by adding the isValidOMS function in the action. partially resolved the issue .

2023-11-09 12:27 UTC, ymaheshwari1 requested changes

2023-11-09 12:27 UTC, ymaheshwari1 commented on src/store/auth.ts
> +      if(oms === "dev-apps"){
Here we have hardcoded the oms value, but then this condition will always return false if we have used any other oms which is not correct.
Need to have some robust solution that can handle all the oms and we also don't need to hardcode oms names for checking.

2023-11-09 12:27 UTC, ymaheshwari1 commented
Closing as need to find some solution that can handle all the oms instances.

2023-11-09 12:27 UTC, closed without merging