Improved: code by adding loader when logging out(#60)
hotwax/launchpad pull request #94
Opened 2024-03-12 13:39 UTC by Ritika-Patel08

### Related Issues

Related Issue #60

### Short Description and Why It's Useful

Added loader when logging out such that users will have a visual cue that their action is in progress which will definitely enhance the user experience. 

### Screenshots of Visual Changes before/after (If There Are Any)

**IMPORTANT NOTICE** - Remember to add changelog entry

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/hotwax/job-manager#contribution-guideline)

2024-03-13 08:59 UTC, amansinghbais commented on src/App.vue
> +
Removed this unnecessary space.

2024-03-13 09:02 UTC, amansinghbais commented on src/store/auth.ts
> +      emitter.emit("presentLoader",{ message: "Logging out...", backdropDismiss: false });
Please check in the translation for this message entry.

2024-03-13 09:03 UTC, amansinghbais commented on src/views/Home.vue
> +import emitter from "@/event-bus";
Remove import for this unused emitter

2024-03-13 09:14 UTC, Ritika-Patel08 commented on src/views/Home.vue
> +import emitter from "@/event-bus";
done.

2024-03-13 09:14 UTC, Ritika-Patel08 commented on src/App.vue
> +
done.

2024-03-14 05:24 UTC, amansinghbais approved these changes

2024-03-15 10:09 UTC, amansinghbais approved these changes

2024-03-15 13:06 UTC, ymaheshwari1 requested changes

2024-03-15 13:06 UTC, ymaheshwari1 commented on src/store/auth.ts
> +      emitter.emit("presentLoader",{ message: "Logging out...", backdropDismiss: false });
Move this inside the if condition of unauthorised check

2024-03-15 13:13 UTC, ymaheshwari1 approved these changes

2024-03-15 13:13 UTC, merged